# Generated by Django 3.1.6 on 2021-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(default='nil', max_length=50)),
                ('modelphno', models.IntegerField(default=5)),
                ('modelemail', models.EmailField(default='nil', max_length=50)),
                ('modelusername', models.CharField(default='nil', max_length=50)),
                ('modelpassword', models.CharField(default='nil', max_length=50)),
                ('modelconfirmpassword', models.CharField(default='nil', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'RegisterTable',
            },
        ),
    ]
