# Generated by Django 3.1.6 on 2021-02-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=150)),
                ('bus', models.CharField(max_length=150)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityapp.stations')),
            ],
        ),
    ]
