# Generated by Django 3.1.6 on 2021-02-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0002_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='day',
            field=models.CharField(default='monday', max_length=150),
        ),
    ]
