# Generated by Django 3.1.6 on 2021-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0004_display_timeinterval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='timeinterval',
        ),
        migrations.AddField(
            model_name='bus',
            name='timeinterval',
            field=models.CharField(default='8:00', max_length=25),
        ),
    ]
